/*
 * Decompiled with CFR 0.137.
 */
package com.jeec.game;

public enum PlayerState {
    WAITING_FOR_GAME_START,
    WAITING_FOR_OTHERS_ROLL_ORDER,
    ROLLING_ORDER,
    ROLLING_ORDER_AGAIN,
    WAITING_FOR_OTHERS_ROLL_ORDER_FIGHT,
    ROLLING_ORDER_FIGHT,
    WAITING_FOR_ORDER_ROLL_FIGHT_VERIFICATION,
    WAITING_FOR_ORDER_ROLL_VERIFICATION,
    ORDER_ROLLED,
    WAITING_FOR_OTHER_INITIAL_BUILD,
    INITIAL_BUILD,
    MY_TURN_BEFORE_ROLLING,
    MY_TURN_ROLLING,
    MY_TURN_ROLLING_AGAIN,
    MY_TURN_WAITING_FOR_VERIFICATION,
    MY_TURN_AFTER_ROLLING,
    OTHERS_TURN,
    ROUND_ENDED,
    GAME_ENDED  ;

}
